menu:
  img: /u/base/logo-h.svg
  items:
  - label: Inicio
    url: /
    anchor: Mamakuna - Terapeuta Holística en Murcia, San Pedro del Pinatar y Torrevieja
  - label: Terapias
    url: /#terapias
    items:
    - label: Limpieza Energética de Cuerpos
      anchor: Limpieza Energética de Cuerpos Online
      url: /limpieza-energetica/
    - label: Círculos de Mujeres
      anchor: Círculos de Mujeres en Murcia, San Pedro del Pinatar y Torrevieja
      url: /circulos-mujeres/
    - label: Sanación de Útero
      anchor: Sanación de Útero en Murcia, San Pedro del Pinatar y Torrevieja
      url: /sanacion-utero/
    - label: Reiki Crístico
      anchor: Reiki Online y en Murcia, San Pedro del Pinatar y Torrevieja
      url: /reiki/
  - label: Sobre mi
    url: /#sobre-mi
  - label: Testimonios
    url: /#testimonios
  - label: ¿Por qué conmigo?
    url: /#por-que-conmigo
  - label: Contacto
    url: /#contacto
    btn: cta
  - label: Eventos
    url: /#eventos
  - label: Blog
    url: /#blog
callnows:
- type: whatsapp
  label: 605 38 01 98
  btn: cta
footer:
  div: ethnic
  div_y: n
  space: 2
  dots:
  - url: https://g.page/r/Cem6Zye01vC0EBM
  - url: https://www.youtube.com/@shalom.mamakuna
  md: |
    - ::copyright::        {{< internal-link index >}}
    - ::balance::          {{< internal-link legal >}}
    - ::encrypted::        {{< internal-link privacy >}}
    - ::cookie::           {{< internal-link cookies >}}
    - ::brand:seacomoseo:: {{< i18n web_design >}} [seacomoseo.com](https://seacomoseo.com/)
    {.list-inline}
